# define arg variable for python version
ARG PYTHON_VER="3.11"

# define base image
FROM python:$PYTHON_VER

# at this point the arg variable PYTHON_VER is null since it has been used up

# define arg varables again
ARG PYTHON_VER="3.11"
ARG QUARTO_VER="1.4.555"
ARG ENV_NAME="quarto-nik"

# environment variables; now they are available elsewhere
ENV ENV_NAME=$ENV_NAME
ENV PYTHON_VER=$PYTHON_VER
ENV QUARTO_VER=$QUARTO_VER

# create directory to copy over files/scripts
RUN mkdir requirements

# copy files
COPY install_quarto.sh install_linux_updates.sh requirements/
COPY packages.txt install_packages.sh requirements/

# Install dependencies
RUN bash ./requirements/install_linux_updates.sh

RUN bash ./requirements/install_quarto.sh $QUARTO_VER

RUN bash ./requirements/install_packages.sh $ENV_NAME $PYTHON_VER
